name: simple-build-test

on: [push]

jobs:
  build:
    name: xorfilter
    runs-on: ubuntu-latest

    steps:
      - name: Install nightly toolchain with clippy available
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: clippy
      - uses: actions/checkout@v1
      - name: Build nightly dev
        run: cargo +nightly build --verbose
      - name: Build nightly release
        run: cargo +nightly build --verbose --release
      - name: Test nightly dev
        run: cargo +nightly test --verbose
      - name: Test nightly release
        run: cargo +nightly test --verbose --release
